Remove libandroid_runtime library dependency
This CL removes unused libandroid_runtime library dependency.
It prevents the ImsStackTest(ITS) crash by removing
libandroid_runtime -> libcycleperuid -> libbpf(private lib) dependencies.

Crash log snippet:
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libbpf.so" not found: needed by /data/app/~~gMD1zisJUs216czacr70DQ==/com.android.imsstack.its-kpqsmYj8TxE49TC5cJIonQ==/base.apk!/lib/x86_64/libcycleperuid.so in namespace clns-11
java.lang.UnsatisfiedLinkError: No implementation found for int com.android.imsstack.jni.JniIms.nativeSendCommand(int, int, byte[]) (tried Java_com_android_imsstack_jni_JniIms_nativeSendCommand and Java_com_android_imsstack_jni_JniIms_nativeSendCommand__II_3B) - is the library loaded, e.g. System.loadLibrary?
```

Test: ABTD test (https://android-build.corp.google.com/abtd/run/L53500030086593285/)
Test: atest ImsStackNativeTests
Test: atest ImsStackJavaTests
Test: Audio/video MO/MT call
Bug: 487469104
Flag: EXEMPT UNSUPPORTED_LANGUAGE
Change-Id: Ia226530d106ce13ec486a3795882acd07b0f2b3a