[C++23] Add missing includes for ImsStack
Add <memory> include for std::shared_ptr declaration. This fixes errors
with C++23 because C++23 removed certain transitive includes.

Errors:
vendor/google/services/ImsStack/native/libimsstack/enabler/include/media/MediaManager.h:42:39:
error: implicit instantiation of undefined template
'std::shared_ptr<MediaSession>'
   42 |         std::shared_ptr<MediaSession> pMediaSession;

Generated by Gemini.

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libimsstack-enabler
Change-Id: I1343281cc9d3932bd9a6512e7d3114e27acdb942